// <auto-generated />
using Escola_Sprint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Escola_Sprint.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Escola_Sprint.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdCurso");

                    b.ToTable("aluno", (string)null);
                });

            modelBuilder.Entity("Escola_Sprint.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<int>("CH_Semanal")
                        .HasColumnType("int");

                    b.Property<int>("CH_Total")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDisciplina"));

                    b.Property<int>("CH")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("codigoprofessor")
                        .HasColumnType("int");

                    b.HasKey("IdDisciplina");

                    b.HasIndex("codigoprofessor");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titularidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Notas", b =>
                {
                    b.Property<int>("IdRelatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRelatorio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRelatorio"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int")
                        .HasColumnName("Ano_letivo");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<float>("Nota1")
                        .HasColumnType("float")
                        .HasColumnName("Nota_1");

                    b.Property<float>("Nota2")
                        .HasColumnType("float")
                        .HasColumnName("Nota_2");

                    b.Property<float>("Nota3")
                        .HasColumnType("float")
                        .HasColumnName("Nota_3");

                    b.HasKey("IdRelatorio");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("notas", (string)null);
                });

            modelBuilder.Entity("aluno_has_disciplinas", b =>
                {
                    b.Property<int>("Aluno_idAluno")
                        .HasColumnType("int");

                    b.Property<int>("Disciplinas_idDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Aluno_idAluno", "Disciplinas_idDisciplina");

                    b.HasIndex("Disciplinas_idDisciplina");

                    b.ToTable("aluno_has_disciplinas");
                });

            modelBuilder.Entity("disciplinas_has_cursos", b =>
                {
                    b.Property<int>("Cursos_idCurso")
                        .HasColumnType("int");

                    b.Property<int>("Disciplinas_idDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Cursos_idCurso", "Disciplinas_idDisciplina");

                    b.HasIndex("Disciplinas_idDisciplina");

                    b.ToTable("disciplinas_has_cursos");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Aluno", b =>
                {
                    b.HasOne("Escola_Sprint.Models.Curso", "Curso")
                        .WithMany("Alunos")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Aluno_Cursos");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Disciplina", b =>
                {
                    b.HasOne("Escola_Sprint.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("codigoprofessor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_disciplinas_professor1");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Notas", b =>
                {
                    b.HasOne("Escola_Sprint.Models.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Notas_Aluno1");

                    b.HasOne("Escola_Sprint.Models.Disciplina", "Disciplina")
                        .WithMany("Notas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Notas_Disciplinas1");

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("aluno_has_disciplinas", b =>
                {
                    b.HasOne("Escola_Sprint.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("Aluno_idAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escola_Sprint.Models.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("Disciplinas_idDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("disciplinas_has_cursos", b =>
                {
                    b.HasOne("Escola_Sprint.Models.Curso", null)
                        .WithMany()
                        .HasForeignKey("Cursos_idCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Escola_Sprint.Models.Disciplina", null)
                        .WithMany()
                        .HasForeignKey("Disciplinas_idDisciplina")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Escola_Sprint.Models.Aluno", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Curso", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Disciplina", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("Escola_Sprint.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
